export const customFieldTypes = ['string', 'number', 'array', 'float', 'binary'];

export const postgresColumnTypes = [
  'bigint',
  'bigserial',
  'bit',
  'bit varying',
  'boolean',
  'box',
  'bytea',
  'character',
  'character varying',
  'cidr',
  'circle',
  'date',
  'double precision',
  'inet',
  'integer',
  'interval',
  'json',
  'jsonb',
  'line',
  'lseg',
  'macaddr',
  'money',
  'numeric',
  'path',
  'pg_lsn',
  'point',
  'polygon',
  'real',
  'smallint',
  'smallserial',
  'serial',
  'text',
  'time',
  'timestamp',
  'tsquery',
  'tsvector',
  'txid_snapshot',
  'uuid',
  'xml',
  // aliases
  'int8',
  'serial8',
  'varbit',
  'bool',
  'char',
  'varchar',
  'float8',
  'int',
  'int4',
  'decimal',
  'float4',
  'int2',
  'serial2',
  'serial4',
  'timetz',
  'timestamptz',
];

export const operatorsMap: { [operator: string]: string } = {
  _eq: '=',
  _neq: '<>',
  _in: 'IN',
  _nin: 'NOT IN',
  _gt: '>',
  _gte: '>=',
  _lt: '<',
  _lte: '<=',
  _isnull: 'IS NULL',
  _like: 'LIKE',
  _ilike: 'ILIKE',
  _nlike: 'NOT LIKE',
};

export const aggregates = ['count', 'min', 'max', 'avg', 'sum'];
